### ISSUE TITLE
Set up flask (API)

### ISSUE THREAD

**Issue by sheng-xu-01** [review-summary/notebooks#3]

**Comment by yerzatm** [comment]
1. Managed to get the code working to get the first 10 reviews (first page)

2. Still working on getting all the reviews from all other pages

3. Works locally, without a nice looking front-end

**Comment by yerzatm** [comment]
1. I rewrote the code to pull all reviews, it worked well for the following links
https://www.amazon.com/product-reviews/B07HG67ZGW/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=1#reviews-filter-bar

https://www.amazon.com/product-reviews/B07BKM4N9B/ref=cm_cr_arp_d_viewopt_kywd?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=1

https://www.amazon.com/product-reviews/B00C1DEFHI/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&filterByStar=all_stars&reviewerType=all_reviews&pageNumber=1#reviews-filter-bar
